### ISSUE TITLE
https://data.alltheplaces.xyz infra down due to invalid https cert

### ISSUE THREAD

**Issue by riordan** [alltheplaces/alltheplaces#11328]
It appears that the various tooling available on data.alltheplaces.xyz is unavailable. This includes the root site, as well as elements like the [spiders from latest run tool](https://www.alltheplaces.xyz/spiders) which depends on www.alltheplaces.xyz/config.json and data.alltheplaces.xyz/history.json

<img width="1078" alt="image" src="https://github.com/user-attachments/assets/73d9d20a-4915-42ed-bab3-80ff304453e2">

**Comment by iandees** [comment]
Thanks for pointing this out. I think this should be resolved.

The `data.alltheplaces.xyz` domain is fronted by Cloudflare, which points to Bunny.net, which points to an S3 bucket. I have the Bunny step in there because they have a really nice feature that signs S3 requests so the bucket doesn't have to be public for the CDN to reach it. The Bunny setup was forcing SSL with the domain `data.alltheplaces.xyz`, and it couldn't regenerate that SSL cert since Cloudflare is doing it. So I disabled SSL in Bunny and it fixed this.
