### ISSUE TITLE
Ford dealerships

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#1162]
https://www.ford.com/services/dealer/Dealers.json?make=Ford&radius=100&filter=&minDealers=1&maxDealers=100&latitude=45.0&longitude=-90.0

**Comment by davidhicks** [comment]
The URL has seemingly changed to e.g.: https://www.ford.com/cxservices/dealer/Dealers.json?make=Ford&radius=50&filter=&minDealers=1&maxDealers=25&city=san+jose

This URL appears to require a custom `Application-id` HTTP header be sent with the request.

However, there is perhaps a better alternative for all Ford dealerships in the USA being https://www.ford.com/dealerships/dealer-directory/browse-all/ or otherwise https://www.ford.com/sitemap.xml with a URL filter for `https://www.ford.com/dealerships/dealer-directory/[a-z]{2}/`.

Ford has different websites in various countries, each with their own separate dealership locators/lists. Thus this issue should address Ford in the USA (ford_us as the spider name) with other countries such as Australia needing separate spiders named as e.g. ford_au.

**Comment by davidhicks** [comment]
Seemingly this issue can be closed due to the inclusion of https://github.com/alltheplaces/alltheplaces/blob/HEAD/locations/spiders/ford_dealers_us.py

**Comment by iandees** [comment]
Yep. Fixed in https://github.com/alltheplaces/alltheplaces/pull/4305.
