### ISSUE TITLE
Scraped data doesn't have names 

### ISSUE THREAD

**Issue by blackmad** [alltheplaces/alltheplaces#1308]
Hey,

I'm working on a project that's considering using alltheplaces data and I'm noticing that as far as I can tell, there's no place in the data that has the nice formatted name of the place locations in it. The filename is a start, but lots of them don't have a good way to go from that to a nice name with spaces, like "thebarrecode.geojson".

There's a "name" field in some scrapers, but it's not required, and I'm noticing is maybe meant for the kind of "subname," for a Quizno's, I see a name of "Franklin Shopping Center" which isn't how I'd want to name it (without prepending Quizno's)

questions
- Has the project ever considered a change where scrapers have a concept of the chain name? Would the project be open to that?
- Why isn't the name field required? Is it meant for chain name, "subname" or full name (chain + sub)?

Thanks,
David

**Comment by iandees** [comment]
Hi David!

I've run into this a couple times when generating output for others. So far I haven't pushed to fix it in the scrapers themselves because the results felt like they would be usecase-specific. For example, should the name of the place be "McDonald's" for all McDonald's worldwide? Or should they have a country code in them so they're unique per scraper? Another common attribute that's missing is a "category" of some sort. Who's category identifiers should be used?

So far we have only scraped facts from websites, we haven't tried to enhance that scraped data with implied information yet.

I'd be ok with adding the chain name. We'd probably want to make it a property of the spider class and then pull the property off when writing out items?

In regards to required properties: almost none of the properties are required. The only thing required from a spider is the `ref` property so it can de-dupe items on the way out to the file. Other stuff isn't listed as required because it's very possible that a spider can't get some of the items. Even lat/lon aren't required, in which case the spiders will output a null geometry in the GeoJSON output.

At least as [currently documented](https://github.com/alltheplaces/alltheplaces/blob/master/DATA_FORMAT.md#properties), "name" is meant to be specific to the place that is scraped. We can add a property for chain name, but I don't think it should be required.

**Comment by nvkelso** [comment]
+💯

**Comment by Cj-Malone** [comment]
If I'm not mistaken, this has been solved with "brand", leaving "name" for the branch name.
