### ISSUE TITLE
Mirabito

### ISSUE THREAD

**Issue by maxerickson** [alltheplaces/alltheplaces#3436]
https://www.mirabito.com/convenience-stores/locations/

**Comment by davidhicks** [comment]
Seems to be using the store finder `WP Go Maps` (`https://wordpress.org/plugins/wp-google-maps/` and `https://www.wpgmaps.com/`). This is an interesting store finder because API calls are obfuscated, looking like:

`https://www.wpgmaps.com/wp-json/wpgmza/v1/marker-listing/base64eJyrVirIKHDOSSwuVrJSCg9w941yjInxTSzKTi3yySwuycxLj4lxSizOTAbxlHSUiksSi0qUrAx0lHJS89JLMpSsDIHs3MSC+MwUINu0FgB6phsI`

`eJyrVirIKHDOSSwuVrJSCg9w941yjInxTSzKTi3yySwuycxLj4lxSizOTAbxlHSUiksSi0qUrAx0lHJS89JLMpSsDIHs3MSC+MwUINu0FgB6phsI` Gzip decompresses to:

`{"phpClass":"WPGMZA\\MarkerListing\\BasicList","start":0,"length":10,"map_id":15}`
