### ISSUE TITLE
"Latest" output endpoint

### ISSUE THREAD

**Issue by ghost** [alltheplaces/alltheplaces#4255]
Currently we have to get the output of a spider on a specific date:

`https://data.alltheplaces.xyz/runs/2022-11-19-13-32-36/output/mcdonalds_fr.geojson`

Could we get something like this to automatically display the latest results?:

`https://data.alltheplaces.xyz/runs/latest/output/mcdonalds_fr.geojson`

Also what are the other available endpoints that could be useful that you use? I remember there was a history.json somewhere. Are they written somewhere? Thanks!

**Comment by iandees** [comment]
Good question. I'll find a spot to add these to the docs:

* [`https://data.alltheplaces.xyz/runs/history.json`](https://data.alltheplaces.xyz/runs/history.json): A JSON array of all known runs and links to their output and logs.
* [`https://data.alltheplaces.xyz/runs/latest.json`](https://data.alltheplaces.xyz/runs/latest.json) A JSON object with the single latest known run.

These two URLs are used to build these HTML pages:
* [`https://www.alltheplaces.xyz/builds.html`](https://www.alltheplaces.xyz/builds.html): A nicer looking summary of the history of all known builds.
* [`https://www.alltheplaces.xyz/spiders.html`](https://www.alltheplaces.xyz/spiders.html): A tabulation of all the output for all the spiders in the 10 most recent builds.

We don't have direct "latest" links to spider output or logs because our current CDN + S3 setup doesn't support redirects. I'll see if I can find a way around that limitation though.

**Comment by Romeo-PHILLIPS** [comment]
Thank you for your answer. I think the "latest" would be quite useful. I often find myself trying to see the latest run of a specific spider, the current way would be to go into history.json, copy the latest date and add it to `https://data.alltheplaces.xyz/runs/<latest_date>/output/mcdonalds_fr.geojson`, which is a bit time consuming.

**Comment by jleedev** [comment]
"Latest" aside, the `spiders.html` table could potentially link to the json at that particular date/spider (or to the html map preview).

**Comment by Romeo-PHILLIPS** [comment]
> "Latest" aside, the `spiders.html` table could potentially link to the json at that particular date/spider (or to the html map preview).

Yea that would be an even better idea

**Comment by iandees** [comment]
I added links to the output for each spider/run combination in the PR above.

**Comment by iandees** [comment]
Also, I confirmed via support ticket with our CDN provider (Bunny.net) that they don't support redirects of the sort we need.

**Comment by Romeo-PHILLIPS** [comment]
Seems to be an issue with `https://www.alltheplaces.xyz/spiders.html` and `https://www.alltheplaces.xyz/builds.html` not displaying anything

**Comment by jleedev** [comment]
Looks like `history.json` got blanked.

**Comment by iandees** [comment]
The file is blanked blanked because the weekly script failed and uploaded the empty version that it hadn't filled up yet. I'll file a bug and fix.
