### ISSUE TITLE
Dunelm spider output is missing 41 branches (dunelm_gb)

### ISSUE THREAD

**Issue by rjw62** [alltheplaces/alltheplaces#4632]
The Dunelm spider dunelm_gb is consistently returning 138 branches for the last few weeks. However, Dunelm's own online store-finder at https://www.dunelm.com/stores/a-z lists 179 branches. All of the 138 are included in the 179, meaning the spider is missing 41.

For example, the following branches appear on Dunelm's website, but aren't returned by the spider:
- https://www.dunelm.com/stores/altrincham
- https://www.dunelm.com/stores/basildon
- https://www.dunelm.com/stores/beckton
- https://www.dunelm.com/stores/beverley

I'm afraid I can't figure out how to manually replicate the spider's request, to check whether the missing branches are missing from the API return, or are just not being picked up by the spider for some reason.

I don't know if there's any connection between the missing stores. The Basildon one only opened recently in April 2022 ([source](https://www.echo-news.co.uk/news/20100489.dunelm-opens-mayflower-retail-park-basildon/)) but the Altrincham store has been around since 2017 ([source](https://www.messengernewspapers.co.uk/news/whereyoulive/15122706.customers-attend-opening-of-dunelms-new-altrincham-store/)). I've checked a few of the missing branches and found facebook supprt groupswith recent posts, suggesting that the stores are indeed still open.

If the API isn't returning all the stores, then perhaps the online list at https://www.dunelm.com/stores/a-z could be used by the spider instead, or maybe https://www.dunelm.com/sitemap/static-sitemap.xml (which also seems to include all 179).

**Comment by Cj-Malone** [comment]
I didn't know any Python before contributing either. Since we're only working on one file, you can completely ignore Git and just use the GitHub website, and you're not really doing much code. I think this is actually the easiest chance you'll ever get.

You go the the [Dunelm spider](https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/dunelm_gb.py) and click the [edit/pencil](https://github.com/alltheplaces/alltheplaces/edit/master/locations/spiders/dunelm_gb.py) button in the top right. Delete line 40. Scroll to "Propose changes" at the bottom, something like "Fix Dunelm crash (closes #4632)" and then click the "Propose changes" button.

If you really don't want to do it, it's fine, I'll do it before the next weekly is ran, but you are clearly technical enough and I think at some stage you're going to go from just consuming to consuming and contributing. It may as well be now.

**Comment by rjw62** [comment]
Ok, I've given it a go. I guess if I'm going to play at fixing individual spiders going forward, I should set up a local copy of the repository and have a way to test-run changes I've made to a specific spider. @Cj-Malone if you're happy to assist me, I'll contact you off-line for advice...

**Comment by Cj-Malone** [comment]
Yeah absolutely, I'm one the OSM US slack quite a bit now, but you've got my email and OSM account so reach out whenever.

The commit looks good, the only thing left is to open the pull request. I think this is the [url](https://github.com/alltheplaces/alltheplaces/compare/master...rjw62:alltheplaces:patch-1), but also if you go to the [pull requests](https://github.com/alltheplaces/alltheplaces/pulls) GitHub may say something like ~"You've just made a change on branch x, do you want to open a PR".
