### ISSUE TITLE
History backup

### ISSUE THREAD

**Issue by Romeo-PHILLIPS** [alltheplaces/alltheplaces#4714]
Hello,
I had seemed to understand if a Spider started failing that the output would still use its latest non failing state. For example `aldi_nord_es` started failing on 2023-01-28 (the latest export) but was working fine 2023-01-21. Due to it failing, the output of `aldi_nord_es` in the global output file is empty.

Would it be possible to if a spider starts failing, to use its latest non failing results state? In this example `aldi_nord_es` to use the ouput of 2023-01-21.

Thank you

**Comment by iandees** [comment]
The "collect the latest successful run" is what our OpenAddresses sister-project does, but All The Places only releases zip files of the results from the latest build. We haven't built the history-aware dump yet because it's currently pretty hard to tell the difference between a spider getting renamed and a spider no longer producing data.

Let's continue conversation in #4351
