### ISSUE TITLE
specsavers_gb spider fail

### ISSUE THREAD

**Issue by rjw62** [alltheplaces/alltheplaces#4842]
After the recent changes I instigated to the specsavers_gb spider, it seems to have failed completely and returned no results in the latest run: https://data.alltheplaces.xyz/runs/2023-02-18-13-32-45/output/specsavers_gb.geojson is empty. Unfortunately, there's nothing in the log files to indicate what happened either: https://data.alltheplaces.xyz/runs/2023-02-18-13-32-45/logs/specsavers_gb.txt is empty.

Is there any way to work out what went wrong here? (Is it an issue with the IP address that the spiders are run from being blocked perhaps?)

More generally, I've seen quite a few spiders returning no results with empty log files. Can/should the logging on the automatic runs be improved, to ensure that when no results are returned something is logged to explain why?

**Comment by Romeo-PHILLIPS** [comment]
I'll also ask something aswell since it seems a bit on topic, what does the read marker mean? The spider works fine locally but could it have a hard time on the server?
<img width="577" alt="Capture d’écran 2023-02-21 à 23 15 51" src="https://user-images.githubusercontent.com/92714362/220470893-510e3d4b-8b8e-42e2-9179-a372c3fd9438.png">

**Comment by iandees** [comment]
> there's nothing in the log files to indicate what happened

This is likely because the spider timed out after 8 hours, which might happen if the other end is blocking us. Maybe we can try to add more logging around this timeout execution to debug that.

> what does the red marker mean?

It means the data for the number of results for that spider has changed by more than one standard deviation over the course of the most recent 10 builds. It should be green when the spider outputs a consistent number of results.

**Comment by davidhicks** [comment]
This spider was deleted in #5319 due to use of Cloudflare bot protection, an issue that is tracked as #4903.

Per discussion in #5432 I think an alternative approach of archiving such spiders is instead desired rather than deletion.

I'll close this issue though as the `specsavers_gb` spider no longer exists, and per #4903 there is no current method built into ATP for bypassing Cloudflare bot protection.
