### ISSUE TITLE
screwfix_gb spider failing

### ISSUE THREAD

**Issue by rjw62** [alltheplaces/alltheplaces#4854]
In the last couple of weeks the screwfix_gb spider has stopped working. It looks like Screwfix have changed their store page URLs, and probably also the formatting of the pages. I can only half fix things though.

First the regex in the line
```rules = [Rule(LinkExtractor(allow=r"\/stores\/(\d+)\/.+$"), callback="parse_sd")]```
needs to be changed to account for the new URLs. The store ID is now two uppercase letters and a number, so something like
```rules = [Rule(LinkExtractor(allow=r"\/stores\/([A-Z][A-Z][0-9])\/.+$"), callback="parse_sd")]```
would work.

However, the StructuredDataParser then fails to extract the data from the store pages. Running
```pipenv run scrapy sd https://www.screwfix.com/stores/AC3/whitby --wanted-types=HardwareStore```
returns
```failed to decode structured data```

The data looks like it's there, e.g. at https://www.screwfix.com/stores/AC3/whitby we have
```<script type="application/ld+json">{&quot;@context&quot;:&quot;https://schema.org&quot;,&quot;@type&quot;:&quot;HardwareStore&quot;,&quot;@id&quot;:&quot;https://www.screwfix.com/stores/AC3/whitby&quot;,&quot;name&quot;:&quot;Screwfix Whitby&quot;,&quot;address&quot;:{&quot;@type&quot;:&quot;PostalAddress&quot;,&quot;addressCountry&quot;:&quot;United Kingdom&quot;,&quot;addressLocality&quot;:&quot;Whitby&quot;,&quot;addressRegion&quot;:&quot;Yorkshire&quot;,&quot;postalCode&quot;:&quot;YO22 4PZ&quot;,&quot;streetAddress&quot;:&quot;Unit 1&quot;,&quot;telephone&quot;:&quot;03330 112 112&quot;},&quot;geo&quot;:{&quot;@type&quot;:&quot;GeoCoordinates&quot;,&quot;latitude&quot;:54.4725969,&quot;longitude&quot;:-0.6019658}}</script>```
I don't know if it's correct HTML or not, but I'm guessing that the `&quot;` encoding may be messing things up for the parser. I'm afraid it's currently beyond me to work out how we should fix this.

FYI, decoding the `&quot;`s in the above, and pretty-printing the JSON, gives
```
{
	"@context": "https://schema.org",
	"@type": "HardwareStore",
	"@id": "https://www.screwfix.com/stores/AC3/whitby",
	"name": "Screwfix Whitby",
	"address": {
		"@type": "PostalAddress",
		"addressCountry": "United Kingdom",
		"addressLocality": "Whitby",
		"addressRegion": "Yorkshire",
		"postalCode": "YO22 4PZ",
		"streetAddress": "Unit 1",
		"telephone": "03330 112 112"
	},
	"geo": {
		"@type": "GeoCoordinates",
		"latitude": 54.4725969,
		"longitude": -0.6019658
	}
}
```

**Comment by Cj-Malone** [comment]
Yeah, so while they have broken data we wont be able to use `StructuredDataSpider`, but we can still use `LinkedDataParser`, we just have to do a bit of the plumbing in the spider code. Do a `git grep "LinkedDataParser\.parse_ld"` or search GitHub for some examples.

In this case, we can't use any of the LinkedDataParser extraction because it trys to parse the data and check the type, so an xpath, probably `response.xpath('//script[@type="application/ld+json"][contains(., "HardwareStore")]/text()').get()`. Then we'll have to fix the data, in this case it looks like it's just html encoding, `html.unescape` should fix that for us. Then `LinkedDataParser.parse_ld` can do all most the parsing. You may also want to do some extras, `StructuredDataSpider` makes sure the website and ref are set, there also might be some other details in the html that may or may not be worth scraping.

**Comment by Cj-Malone** [comment]
If you get stuck let me know :P

**Comment by rjw62** [comment]
Ok, after following your suggestions and a bit of playing, I've come up with the following: https://github.com/rjw62/alltheplaces/blob/0ff64f2e2fb958b1337fbb3b07baf6604bca50a6/locations/spiders/screwfix_gb.py . It gives me 840 branches when run locally, which seems about right. I'm not sure about the coding style and robustness, but it seems to work for now.

Any comments/feedback @Cj-Malone?

**Comment by Cj-Malone** [comment]
The only important thing is the `download_delay`. We do 1 second as default now to try to not annoy them, we only do it lower when we need to.

**Comment by rjw62** [comment]
PR has been merged, and the spider is working again.
