### ISSUE TITLE
Choice Hotels wikidata

### ISSUE THREAD

**Issue by Cj-Malone** [alltheplaces/alltheplaces#5354]
https://github.com/alltheplaces/alltheplaces/blob/3274d8f7b7f3bdb84d94ad6b93d3de70cd2b22fa/locations/spiders/choicehotels.py#L18-L31

A bunch of the Wikidata entries have been deleted, on notability grounds. I'm unsure if they actually didn't meet the notability criteria, or if entries were too vague.

If we can't restore/remake these entries we will have to manually categorise in code, then we'd lose the possibility of any brand level data, social media, logos etc.

cc @MisterSynergy

**Comment by 1ec5** [comment]
Sometimes deletions happen by mistake because the item doesn’t do a great job of explaining why its subject is notable and there isn’t any additional context. To [appeal these deletions](https://www.wikidata.org/wiki/Wikidata:Guide_to_requests_for_undeletion#How_to_request_undeletion) and get a second chance at establishing notability, try contacting an administrator on their Wikidata talk page or [IRC](https://www.wikidata.org/wiki/Wikidata:IRC).

The easiest way to prevent this from happening again is to add the brands to the name suggestion index. There’s a bot that goes around adding [OSM Name Suggestion Index ID (P8253)](https://www.wikidata.org/wiki/Property:P8253) statements to brand items. As an external reference, any such statement [helps to establish notability](https://www.wikidata.org/wiki/Q62589316) or at least gives administrators a hint that the item is being used somewhere.

In these cases, another straightforward step would’ve been to have the [Choice Hotels (Q1075788)](https://www.wikidata.org/wiki/Q1075788) item link to each of these chains using the [has subsidiary (P355)](https://www.wikidata.org/wiki/Property:P355) or [owner of (P1830)](https://www.wikidata.org/wiki/Property:P1830) property.

[Here are more ideas](https://wiki.openstreetmap.org/wiki/Key:brand:wikidata#Establishing_notability) for building out an item to reflect its true notability.

**Comment by Cj-Malone** [comment]
Thanks @1ec5. Recently I've been ensuring NSI and ATP match, adding a bunch of brands to NSI. I will definitely be adding these to NSI.

Same with Wikidata, it's in our and ATP consumers interest to ensure Wikidata is as full as possible. If they are undeleted I'll be adding as much data as I can to them.

**Comment by 1ec5** [comment]
To contact the administrator, post a message on [_their_ user talk page](https://www.wikidata.org/wiki/User_talk:MisterSynergy) or [send them an e-mail](https://www.wikidata.org/wiki/Special:EmailUser/MisterSynergy).

**Comment by Cj-Malone** [comment]
[This one](https://www.wikidata.org/wiki/Wikidata:Guide_to_requests_for_undeletion#How_to_request_undeletion) says I can ping them from my talk page. I'll give them a few days, if they don't respond I'll go to there talk page.

**Comment by 1ec5** [comment]
In order to ping a user on a different page, you need to use the `{{ping|…}}` template.

**Comment by MisterSynergy** [comment]
Hey all, an informal request on the admin's user talk page is the safest path to get their attention. However, there is no formal procedure for undeletion requests defined, so you could ask on the admin's noticeboard or elsewhere on Wikidata using `{{Ping|Username}}` as well.

**Comment by Cj-Malone** [comment]
Thanks everyone, I've updated [NSI](https://github.com/osmlab/name-suggestion-index/commit/ca41b6d2e534320c08f4760ec0338c91de2441ce) now, the reason OSM didn't contain any of these Q IDs was these brands pointed to the parent organisation in NSI, now NSI has the specific brands they will propagate through OSM, with time.

I've turned one of them into a [redirect](https://www.wikidata.org/wiki/Q113152454?redirect=no) as there was already an established entry. I'll update ATP tomorrow.

Thanks again everyone.
