### ISSUE TITLE
24/7 opening hours

### ISSUE THREAD

**Issue by Cj-Malone** [alltheplaces/alltheplaces#6537]
Technically 24/7 means Mo-Su,PH 00:00-24:00, but we mean Mo-Su 00:00-24:00. We should probably change to output the latter.

**Comment by davidhicks** [comment]
There are a few exceptions that typically come to mind (all of which show at least once in ATP):
- Hospitals
- Police stations
- Fuel stations

Perhaps the default case becomes output of `Mo-Su 00:00-24:00`, and this can be changed on a spider-by-spider basis by calling a new method `OpeningHours.add_holiday_hours(..)`?

**Comment by iandees** [comment]
I don't really want to support the complexities of OSM's opening_hours tag. I want to stick to the simplified day range/time range that we have and I don't think we should add support for special extensions like "PH" to All the Places.

I could see it being useful to support opening hours for a specific date (i.e. 2023-12-25 is closed), since we see that on business pages relatively frequently.

**Comment by Cj-Malone** [comment]
Spiders would still welcome to output "24/7" as a string for those categorise.

PH confuses me a little, public holiday opening times aren't equal. There will be a lot of places that open for usual holidays, but a lot of them are closed for Christmas. Right now, I would vote with Ian to avoid adding that to ATP.

Technically OSM does support specific days eg `Mo-Su 08:00-22:00; 2023 Dec 25 10:00-20:00` and off/closed eg `Mo-Su 08:00-22:00; 2023 Dec 25 off`. We don't currently support `off`, my only argument against it is that we wouldn't want to get it wrong. IIRC on of Mateuszs issues was we outputted Monday to Saturday, not Sunday, which he assumed Sunday off, but actually is was just missing from the source data.

**Comment by matkoniecz** [comment]
> which he assumed Sunday off, but actually is was just missing from the source data.

it was #5888
