### ISSUE TITLE
ci/run_all_spiders needs updating with new URLs?

### ISSUE THREAD

**Issue by davidhicks** [alltheplaces/alltheplaces#6613]
Based on https://github.com/alltheplaces/alltheplaces.xyz/commit/6c37dbc36785011ba768f312144286349abf3b9d, is it necessary to change references to "alltheplaces.xyz" in ci/run_all_spiders.sh to "alltheplaces-data.openaddresses.io"?

The last weekly run was 23 December so something is currently broken with the weekly run.

**Comment by iandees** [comment]
Thanks for pointing this out.

I am using Cloudflare's [Sippy](https://blog.cloudflare.com/sippy-incremental-migration-s3-r2/) product to serve data from their storage product R2 instead of through BunnyCDN + AWS's S3. R2+Sippy is free egress and cheap storage whereas we have to pay for BunnyCDN bandwidth + S3 bandwidth and storage. When someone requests an object from Sippy, it will first check to see if it's in R2. If it isn't, it fetches it from the same location on the configured S3 bucket, serve it to the requester and store it in R2 for future requests.

This works great for data that doesn't change, but it looks like Sippy will not attempt to re-fetch data once it's stored it in R2. The latest.json and history.json files that power the download link on the website + the inspection pages was fetched once a couple weeks ago and hadn't been updated since.

To resolve this, I adjusted the URLs so that all references to latest.json or history.json will continue through the old path of Bunny CDN + S3, but the links in those files will point to the Sippy + R2 links that are cheaper.

Hopefully this will allow fresh data to show up while also saving us money on data egress costs.
