### ISSUE TITLE
Hardee's

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#8]

**Comment by ianmcorvidae** [comment]
n.b. Carl's Jr is the name of this in some parts of the country, dunno if that's the same store locator or separate

**Comment by eusid** [comment]
I was able to find the API through the HAR file. It gives results 25 at a time. Must use zipcode, city, or state. There will be a lot of over lap since it always gives 25 results every time no matter how much you narrow the search.  I was worried about dupes due to overlap so I peeked at the pipelines and found item['ref'] on Hardees there are item ids so I could use that to set item['ref']. If there were not item IDs how would I set this value?

**Comment by eusid** [comment]
@ianmcorvidae You are right there are Carls Jr stores in mexico and 1 in texas, and also Carls Green Burrito looks like in texas only

**Comment by eusid** [comment]
@iandees I was hoping you would give me the go ahead to use zipcodes on Hardees and Carls Jr locations. I'm open to any suggestions because especially in rural areas we will get the same 25 Hardees over and over again. Nathaniel told me to contact you.

**Comment by eusid** [comment]
@iandees unassigning myself and looking at some of the new ones that have been posted. if you want to give the go ahead on zip codes or suggest another method I will pick this one back up. Thanks.
