### ISSUE TITLE
verizon_us is empty due to migration to a new website (which appears to be geoblocked, help by someone from USA welcome)

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#8662]
spider: https://github.com/alltheplaces/alltheplaces/blob/master/locations/spiders/verizon_us.py

https://www.alltheplaces.xyz/spiders shows it being consistently at 0

https://www.verizonwireless.com/sitemap_storelocator.xml lists nonzero number of entries such as

- https://www.verizonwireless.com/stores/pennsylvania/reading/gowireless-berkshire-mall-a00000282969/
- https://www.verizonwireless.com/stores/new-york/bay-shore/russell-cellular-south-shore-mall-a00000282964/
- https://www.verizonwireless.com/stores/nevada/las-vegas/rainbow-north-1020691/

but note that entries redirect - https://www.verizonwireless.com/stores/new-york/bay-shore/russell-cellular-south-shore-mall-a00000282964/ goes to https://www.verizon.com/stores/details/new-york/bay-shore/russell-cellular-south-shore-mall-a00000282964/ - maybe format has changed?

https://alltheplaces-data.openaddresses.io/runs/2024-06-15-13-31-46/stats/verizon_us.json lists it as finished

https://alltheplaces-data.openaddresses.io/runs/2024-06-15-13-31-46/logs/verizon_us.txt shows no errors... If it would be failing on redirect or parsing errors would be there, right?

(I silenced reports about broken.empty geojson files for now in my processing - not sure whether such issues without matching PR are useful and likely to be processed)

**Comment by davidhicks** [comment]
The issue is www.verizonwireless.com being retired and replaced with www.verizon.com so the `verizon_us` spider is filtering/preventing off-site requests from the allowed domain www.verizonwireless.com to disallowed domain www.verizon.com

I had a look at https://www.verizon.com/robots.txt for an equivalent sitemap and https://www.verizon.com/sitemap-stores-old.xml does exist, but the "old" in the path makes me question the accuracy. The www.verizon.com/stores page allows a geographic search for locations via an API, but I always get back a HTTP 417 error which I assume is geographic blocking measures. Perhaps someone in the US can confirm what the API call should be, whether it works, whether it is useful to implement, etc. Then we can decide whether the API should be used, or https://www.verizon.com/sitemap-stores-old.xml should be used.
