### ISSUE TITLE
Mark Zyte spiders somehow

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#8791]
Maybe I missed it but it seems that Zyte spiders are not marked specially in output data. 

It would be useful to have this info in spider data as it would allow to more confidently switch to older data release if latest is empty - and to downgrade reports about spider failures. 

Or should data consumer interested in doing this parse spider source code and/or error logs instead?

**Comment by iandees** [comment]
Data consumers shouldn't care about how the data is retrieved.

Can you say more about what you're trying to do?

**Comment by matkoniecz** [comment]
(1) I want to distinguish 
(a) data likely becoming invalid (maybe website broke because they were bought and closed half of location)
(b) proxy failed, dataset from previous run can be safely reused

(2) I want to try fixing broken spiders, maybe list what requires attention - and spiders that failed due to proxy should be ignored here 

Though admittedly for both cases "Zyte proxy failed" would be even better - maybe I should parse error logs after all?

**Comment by davidhicks** [comment]
Ideally I've like to visit https://www.alltheplaces.xyz/spiders and see a "Not run" (or some other indication) against spiders which are expected to require a proxy, and because the run was completed without a proxy, the spiders weren't run. They're not returning 0 results because the spider failed, they're returning 0 results because a proxy wasn't used.

https://github.com/alltheplaces/alltheplaces/blob/master/ci/run_all_spiders.sh could be updated so that "_results.json" includes a `"skipped"` property against each spider, with allowed values being `["proxy_needed"]` (allowing maybe other reasons to be added in the future too).

**Comment by matkoniecz** [comment]
looking into it again: https://alltheplaces-data.openaddresses.io/runs/2024-07-06-13-31-59/stats/daylight_donuts_us.json has such info!


`"finish_reason": "zyte_api_suspended_account",` should work well
