### ISSUE TITLE
Lowe's

### ISSUE THREAD

**Issue by ianmcorvidae** [alltheplaces/alltheplaces#88]
https://www.lowes.com/store/

**Comment by nicolas17** [comment]
GET https://www.lowes.com/wcs/resources/store/10151/storelocation/v1_0?maxResults=30&query=<ZIPCODE>.

If I set maxResults high enough, I get 221 stores, which might be all of them (in which case the specific zipcode used doesn't matter as long as it's valid). Needs more testing to ensure that's the case, or maybe finding out elsewhere if they do have 221 stores and not more.

**Comment by ianmcorvidae** [comment]
https://en.wikipedia.org/wiki/Lowe%27s says 1.840 stores, so probably not.

**Comment by iandees** [comment]
No progress for 2 days, re-opening this for others.

**Comment by ethan626** [comment]
This link is broken. 
https://www.lowes.com/wcs/resources/store/10151/storelocation/v1_0?maxResults=30&query=

Attempted to use https://lowes.com/store, this will yeild at most 10 items. So it appears that one is required to enter new search items in order to recieved new locations. 

Looking for a workaround. 
A potential solution is brute force. Generate all possible zip codes and search using those. (This does lead to a very large number of requests) 

Ideas?

**Comment by ethan626** [comment]
Using a state as a search query or setting the max results to a very high number does not seem to work. The response will only return a max of ten locations. The proposed solution is to generate zip codes and use those as search queries.
