### ISSUE TITLE
le_crobag_de - remove trailing comma from `addr:city=Berlin,`

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#8956]
It surely should be `addr:city=Berlin` rather than `addr:city=Berlin,`

**Comment by matkoniecz** [comment]
maybe this should go into some general address data cleanup rather than having such fixes scattered across code?

**Comment by CloCkWeRX** [comment]
Maybe, but also knowing our luck someone will ironically rename a minor city to a series of emojis or wingdings or a utf8 rendering that is 100% valid in a local language but falls afoul of global rules.

https://en.m.wikipedia.org/wiki/Wikipedia:Naming_conventions_(geographic_names) is the closest I can find to "rules for naming your city".

Suggest we put it in place in the one spot we see it for now, but refactor if we hit 5? examples more to make it an opt in?
Or something that raises an exception to reject, rather than silently strip?
