### ISSUE TITLE
Pizza Hut

### ISSUE THREAD

**Issue by iandees** [alltheplaces/alltheplaces#9]
```
curl 'https://www.pizzahut.com/api.php/site/api_ajax/find_nearby' \
 -H 'Accept: application/json, text/plain, */*' \
 -H 'Referer: https://www.pizzahut.com/' \
 --data-binary '{"occasion":"C","zip":"24450","near":"24450","address":"","dine_in":false,"store_limit":10,"mob_find":true}'
```

**Comment by AustenHolmberg** [comment]
A bit stumped by this one, the only way to get the data seems to be to send a request to their api (like the one mentioned in iandees's comment) that uses a cookie which likely expires. Unassigning myself for now.

**Comment by vlad555** [comment]
Hello
Same situation as Subway and Wallgreens
Just need lat/lon pair and we can request:
https://locator-svc.subway.com/v2//GetLocations.ashx?q={"InputText":"","GeoCode":{"Latitude":47.5768927,"Longitude":-120.20598330000001,"Accuracy":null,"CountryCode":"US","RegionCode":null,"PostalCode":null,"City":null,"LocalityType":null},"DetectedLocation":{"Latitude":0,"Longitude":0,"Accuracy":0},"Paging":{"StartIndex":1,"PageSize":10},"ConsumerParameters":{"metric":false,"culture":"en-US","country":"US","size":"D","template":"","rtl":false,"clientId":"17","key":"SUBWAY_PROD"},"Filters":[],"LocationType":2}

**Comment by whoissteven** [comment]
Work stopped, safe for me to reassign to myself? I can tackle this right now.

**Comment by nvkelso** [comment]
Yes

**Comment by whoissteven** [comment]
Are we allowed to use splash to render javascript on page?

**Comment by vlad555** [comment]
As developer, who already analyzed Pizza Hut I can say it's not necessary to render any javascript on this site to grab data.
Only one problem I see - searching by position or ZIP.
Last time I used to scan all USA ZIPs, I got message I shouldn't use this method because of huge amount of requests and overlapped zones.
Correct me if I wrong, please. Do you find another way to scan it?

By the way, question about splash interested me too, because I have javascript-building site to scrap.

**Comment by iandees** [comment]
This issue hasn't been worked on in a while. I'm removing the assignment so others can work on it. If you're still working on it, please reassign yourself and reference a pull request or branch where you're doing your work.

**Comment by thismakessand** [comment]
Looks like zipcode search no longer needed:  https://locations.pizzahut.com/
