### ISSUE TITLE
maybe throw away empty address fields?

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#9241]
small sample of `value.replace("-", "").replace("–", "").strip() == ""` checks:

```
mercedes_benz_group has addr:postcode = -
mercedes_benz_group has addr:state = -
esprit has addr:postcode = --
caltex has addr:street = -
caltex has addr:street = -
caltex has addr:street = -
dr_max has addr:street_address = -
scania has addr:postcode = 
dulux_decorator_centre_gb has addr:city = -
dulux_decorator_centre_gb has addr:city = -
dulux_decorator_centre_gb has addr:city = -
mol has addr:street_address = -
mol has addr:street_address = -
mol has addr:street_address = -
subway_kr has addr:full = -
nespresso has addr:postcode = -
bp has addr:postcode = -
total_energies has addr:postcode = -
```

(very large number of lines, including for spiders mentioned here, were skipped)

**Comment by davidhicks** [comment]
Agreed with resetting to `None` in a pipeline for any of these fields which are blank strings. Although sometimes in ATP, instead of setting fields to `None`, the field gets deleted altogether. I prefer keeping the field though to try and avoid code paths having to check if a field exists before use.
