### ISSUE TITLE
Add labels for difficulty, quality?

### ISSUE THREAD

**Issue by CloCkWeRX** [alltheplaces/alltheplaces#9347]
We have labels for "good first issue", but not as much for "hard work spider" or things in between.

IE is translating a JSON API with DictParser trivial, or will you have to add post processing and clean out closed locations for SEO purposes using a series of obsfucated keys?

Could we look at a broad indicator of "sizing/complexity" (easy, medium, hard, too hard)?

This would allow us to put links in the readme or adjust the sticky post for "how to help" to point new contributors to low hanging fruit.

**Comment by CloCkWeRX** [comment]
@davidhicks I would be interested in your opinion on if this is valuable, as you do a lot of triage and backlog grooming

**Comment by davidhicks** [comment]
The hard part I think is deciding what makes something easy, difficult, etc. I've been using "good first issue" for the simplest ones (e.g. StructuredData, simple store finders, simple HTML parsing of pages from a sitemap) and everything else I'd currently classify as being of a moderate difficulty, except a handful of cases where I'd say it is "hard" because there is ideally a core library of ATP that needs new supporting features, such as handling some more complex types of geographic radius/box searches.
